"DbUser" = "admina136186@sertechdbserver"
"DbPassword" = "A$dmin12345678910"
"DbName" = "app"
"DbPort" = "5432"
"DbHost" = "sertechdbserver.postgres.database.azure.com"
"ListenHost" = "0.0.0.0"
"ListenPort" = "3000"