steps:
  - task: ShellScript@2
    displayName: Build GoLang Solution
    inputs:
      scriptPath: '$(Build.Repository.LocalPath)/build.sh'
      failOnStandardError: false

  - task: CmdLine@2
    displayName: Execute data feed and DB Migration
    inputs:
      script: ./SerTechChallenge updatedb
      workingDirectory: '$(Build.Repository.LocalPath)/dist'
      failOnStderr: false

  - task: Docker@2
    displayName: Build and Push image to ACR
    inputs:
      command: buildAndPush
      repository: sertechchallenge-docker
      Dockerfile: '$(Build.Repository.LocalPath)/Dockerfile'
      containerRegistry: techappacrserviceconnection
      tags: latest

  - publish: $(Build.Repository.LocalPath)/pipelines
    artifact: sertechchallenge